print("Name: Md. Mahfuzur Rahman Bhuyan")
print("Email: mdmahfuzurrahmanbhuyan@gmail.com")
print("Slack Username: @Mahfuz")
print("Biostack: Genomics")
print("Twitter: @RobyRahman13")
print("Hamming Distance: 1")
